#!/usr/bin/env python
from AudioPlayer import AudioPlayer
import tkinter as tk

def handle_btnPlayPause(player, btn, btnText):
    if player.get_status()=="Playing":
        player.pause()
        btnText.set("Play")
        btn.pack(expand=True,fill='both')
    else:
        player.play()
        btnText.set("Pause")
        btn.pack(expand=True,fill='both')
    print "    status:", player.get_status()

def ui(canvas, player):
    btnText = tk.StringVar()
    btnText.set("Play")
    btnPlayPause = tk.Button(canvas, textvariable=btnText, font=("MS",12,"bold"), \
                             command = lambda: handle_btnPlayPause(player, btnPlayPause, btnText) )
    btnPlayPause.pack(expand=True,fill='both')

player = AudioPlayer()
current_audio_file = player.get_last_played_audio_file()
player.set_audio_file(current_audio_file)

root = tk.Tk()
root.attributes('-zoomed', True)
#root.grid_columnconfigure(0, weight=1)
screen_width = root.winfo_screenwidth()
screen_height = root.winfo_screenheight()
canvas = tk.Canvas(root, width=screen_width, height=screen_height)
ui(canvas, player)
canvas.pack( expand=True, fill='both')

tk.mainloop()
