#!/usr/bin/env python
from vlc_dbus import VLC
import tkinter as tk

def handle_btnPlayPause(canvas, vlc):
    if player.get_status()=="Playing":
        player.pause()
    else:
        player.play()
    print "    status:", vlc.get_status()

def ui(canvas, player):
    btnPlayPause = tk.Button(canvas, text="Play", font=("MS",12,"bold"), \
                             command = lambda: handle_btnPlayPause(canvas, player) )
    btnPlayPause.pack(expand=True,fill='both')

player = AudioPlayer()
if player.isNewBook():
    player.setToFirstAudioFile()
else:
    current_audio_file = player.get_current_audio_file()
player.add_audio_file(os.getcwd() +"test.mp3")
player.pause()

root = tk.Tk()
root.attributes('-zoomed', True)
#root.grid_columnconfigure(0, weight=1)
screen_width = root.winfo_screenwidth()
screen_height = root.winfo_screenheight()
canvas = tk.Canvas(root, width=screen_width, height=screen_height)
ui(canvas, vlc)
canvas.pack( expand=True, fill='both')

tk.mainloop()
